import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from "react";
import type { ExtensionPaneProps } from "hunkdiff/extension";

import {
  checkpointStatus,
  checkpointSummary,
  currentSection,
  currentSectionFocus,
  currentTarget,
  getGuideSnapshot,
  guideProgress,
  reviewStatus,
  selectSection,
  selectTarget,
  showOverview,
  subscribeGuide,
  targetResolution,
  toggleCurrentReviewed,
  toggleCurrentSectionReviewed,
  toggleShowAllChanges,
  unrepresentedFiles,
  visibleSections,
  type CheckpointStatus,
  type FileCheckpointStatus,
} from "./state.ts";
import { syncGuidePresentation } from "./presentation.ts";

function fit(text: string, width: number) {
  if (text.length <= width) return text;
  return width <= 1 ? text.slice(0, width) : `${text.slice(0, width - 1)}…`;
}

function shortSourcePath(path: string) {
  const parts = path.split(/[\\/]/).filter(Boolean);
  return parts.slice(-2).join("/") || path;
}

function wrap(text: string, width: number): readonly string[] {
  const lines: string[] = [];
  let current = "";
  for (const word of text.split(/\s+/).filter(Boolean)) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= width) {
      current = next;
    } else {
      if (current) lines.push(current);
      current = fit(word, width);
    }
  }
  if (current) lines.push(current);
  return lines.length > 0 ? lines : [""];
}

function reviewGlyph(status: ReturnType<typeof reviewStatus>) {
  if (status === "reviewed") return "✓";
  if (status === "stale-reviewed") return "⚠";
  return " ";
}

function targetCheckpointLabel(status: CheckpointStatus) {
  if (status === "changed") return "~ changed";
  if (status === "new") return "+ new target";
  if (status === "missing") return "! missing";
  if (status === "unknown") return "? unknown";
  return "";
}

function fileCheckpointLabel(status: FileCheckpointStatus) {
  if (status === "changed") return "~ changed";
  if (status === "new") return "+ new file";
  if (status === "unknown") return "? unknown";
  return "  unchanged";
}

function countLabel(count: number, singular: string) {
  return `${count} ${singular}${count === 1 ? "" : "s"}`;
}

function checkpointColor(
  status: CheckpointStatus | FileCheckpointStatus,
  theme: ExtensionPaneProps["theme"],
) {
  if (status === "changed") return theme.fileModified;
  if (status === "new") return theme.fileNew;
  if (status === "missing") return theme.fileDeleted;
  if (status === "unknown") return theme.badgeNeutral;
  return theme.text;
}

export function GuidePane({
  width,
  height,
  theme,
  keybindings,
  actions,
  reviewGeneration,
}: ExtensionPaneProps): ReactNode {
  const state = useSyncExternalStore(subscribeGuide, getGuideSnapshot);
  const [providerClock, setProviderClock] = useState(Date.now());
  useEffect(() => {
    if (state.provider.status !== "running") return;
    setProviderClock(Date.now());
    const timer = setInterval(() => setProviderClock(Date.now()), 1_000);
    return () => clearInterval(timer);
  }, [state.provider.status, state.provider.startedAt]);
  const providerElapsed = state.provider.startedAt
    ? Math.max(0, Math.floor((providerClock - state.provider.startedAt) / 1_000))
    : null;
  const providerLine = ` provider: ${state.provider.status}${state.provider.message ? ` · ${state.provider.message}` : ""}${providerElapsed !== null ? ` · ${providerElapsed}s/${state.provider.timeoutSeconds}s` : ""}`;
  const actionsRef = useRef(actions);
  actionsRef.current = actions;
  const sourceLabel =
    state.source?.kind === "file"
      ? shortSourcePath(state.source.path)
      : state.source?.kind === "generated"
        ? `generated by ${state.source.provider} · ${state.source.stale ? "earlier changeset" : state.source.savedPath ? `saved to ${state.source.savedPath}` : "unsaved"}`
        : null;
  const innerWidth = Math.max(8, width - 2);
  const sections = visibleSections(state);
  const section = currentSection(state);
  const target = currentTarget(state);
  const sectionIndex = section
    ? sections.findIndex((candidate) => candidate.id === section.id)
    : -1;
  const progress = guideProgress(state);
  const focus = currentSectionFocus(state);
  const summary = checkpointSummary(state);
  const summaryParts = [
    summary.changedTargets > 0 ? `~ ${countLabel(summary.changedTargets, "changed target")}` : null,
    summary.missingTargets > 0 ? `! ${countLabel(summary.missingTargets, "missing target")}` : null,
    summary.newTargets > 0 ? `+ ${countLabel(summary.newTargets, "new target")}` : null,
    summary.changedFiles > 0
      ? `~ ${countLabel(summary.changedFiles, "changed outside file")}`
      : null,
    summary.newFiles > 0 ? `+ ${countLabel(summary.newFiles, "new outside file")}` : null,
    summary.unknownTargets > 0 ? `? ${countLabel(summary.unknownTargets, "unknown target")}` : null,
    summary.unknownFiles > 0 ? `? ${countLabel(summary.unknownFiles, "unknown file")}` : null,
  ].filter((part): part is string => part !== null);
  const visibilityFiltered = progress.visibleTargetCount !== progress.targetCount;
  const unrepresented = unrepresentedFiles(state).filter(
    (file) => state.scope === "all" || file.status !== "unchanged",
  );
  const previousSectionKey = keybindings.getKeys("hunk-guide.previous-section")[0] ?? "menu";
  const nextSectionKey = keybindings.getKeys("hunk-guide.next-section")[0] ?? "menu";
  const previousTargetKey = keybindings.getKeys("hunk-guide.previous-target")[0] ?? "menu";
  const nextTargetKey = keybindings.getKeys("hunk-guide.next-target")[0] ?? "menu";
  const targetReviewedKey = keybindings.getKeys("hunk-guide.toggle-reviewed")[0] ?? "menu";
  const sectionReviewedKey = keybindings.getKeys("hunk-guide.toggle-section-reviewed")[0] ?? "menu";
  const presentationKey = keybindings.getKeys("hunk-guide.toggle-presentation")[0] ?? "menu";
  const toggleKey = keybindings.getKeys("hunk-guide.toggle")[0] ?? "menu";
  const targetReviewed = target ? reviewStatus(target.id, state) === "reviewed" : false;
  const sectionReviewed =
    section?.targets.every((entry) => reviewStatus(entry.id, state) === "reviewed") ?? false;

  useEffect(() => {
    syncGuidePresentation(actionsRef.current, reviewGeneration, state);
    return () => actionsRef.current.clearPresentationScope();
  }, [reviewGeneration, state.overview, state.resolution, state.sectionId, state.showAllChanges]);

  function syncPresentation() {
    if (syncGuidePresentation(actions, reviewGeneration) === "rejected") {
      actions.notify("Section focus unavailable; showing all changes", "warning");
    }
  }

  function revealSelected(targetId: string) {
    const selected = currentTarget();
    const resolution = targetResolution(targetId);
    syncPresentation();
    if (selected?.id === targetId && resolution?.status === "resolved") {
      actions.revealLine(resolution.runtimeId, selected.side, selected.startLine);
    } else {
      actions.notify("Guide target is unavailable in this changeset", "warning");
    }
  }

  function reveal(targetId: string) {
    const selected = selectTarget(targetId);
    if (selected) revealSelected(selected.id);
  }

  function revealSection(sectionId: string) {
    const selected = selectSection(sectionId);
    if (selected) revealSelected(selected.id);
  }

  return (
    <scrollbox
      width="100%"
      height={height}
      scrollY={true}
      focused={false}
      rootOptions={{ backgroundColor: theme.panel }}
      wrapperOptions={{ backgroundColor: theme.panel }}
      viewportOptions={{ backgroundColor: theme.panel }}
      contentOptions={{ backgroundColor: theme.panel }}
      verticalScrollbarOptions={{ visible: false }}
      horizontalScrollbarOptions={{ visible: false }}
    >
      <box style={{ width: "100%", flexDirection: "column", backgroundColor: theme.panel }}>
        <text
          content={fit(" ◆ GUIDE", innerWidth)}
          style={{ fg: theme.accent, bg: theme.panel }}
          onMouseDown={(event) => {
            if (event.button === 0) {
              showOverview();
              actions.clearPresentationScope();
            }
          }}
        />
        {state.guide ? (
          <>
            <text
              content={fit(
                ` ${state.guide.title ?? state.guide.id}  ${sectionIndex >= 0 ? `${sectionIndex + 1}/${sections.length}` : "overview"}`,
                innerWidth,
              )}
              style={{ fg: theme.text, bg: theme.panel }}
            />
            {sourceLabel && (
              <text
                content={fit(
                  ` ${state.guide.title ? `${state.guide.id} · ` : ""}${sourceLabel}`,
                  innerWidth,
                )}
                style={{ fg: theme.muted, bg: theme.panel }}
              />
            )}
            {state.provider.configured && (
              <text
                content={fit(providerLine, innerWidth)}
                style={{
                  fg:
                    state.provider.status === "failed"
                      ? theme.badgeRemoved
                      : state.provider.status === "running"
                        ? theme.accent
                        : theme.muted,
                  bg: theme.panel,
                }}
              />
            )}
            <text
              content={fit(
                visibilityFiltered
                  ? ` ${progress.visibleReviewedCount}/${progress.visibleTargetCount} visible · ${progress.reviewedCount}/${progress.targetCount} total · ${state.scope}`
                  : ` ${progress.reviewedCount}/${progress.targetCount} targets reviewed · ${state.scope}`,
                innerWidth,
              )}
              style={{ fg: theme.accentMuted, bg: theme.panel }}
            />
            {progress.hiddenKinds.length > 0 && (
              <text
                content={fit(` hidden: ${progress.hiddenKinds.join(", ")}`, innerWidth)}
                style={{ fg: theme.accentMuted, bg: theme.panel }}
              />
            )}
            <text
              content={fit(
                ` [${state.showAllChanges ? "✓" : " "}] Show all changes  ${presentationKey}`,
                innerWidth,
              )}
              style={{ fg: state.showAllChanges ? theme.text : theme.accent, bg: theme.panel }}
              onMouseDown={(event) => {
                if (event.button === 0) {
                  toggleShowAllChanges();
                  syncPresentation();
                }
              }}
            />
            {focus && (
              <text
                content={fit(
                  ` ${countLabel(focus.hunkCount, "hunk")} in ${countLabel(focus.fileCount, "file")} · ${countLabel(focus.hiddenFileCount, "file")} hidden`,
                  innerWidth,
                )}
                style={{ fg: theme.accentMuted, bg: theme.panel }}
              />
            )}
            {state.checkpoint &&
              wrap(
                summaryParts.length > 0
                  ? `since checkpoint: ${summaryParts.join(" · ")}`
                  : "since checkpoint: no changes",
                innerWidth - 1,
              ).map((line, index) => (
                <text
                  key={`checkpoint-summary:${index}`}
                  content={fit(` ${line}`, innerWidth)}
                  style={{ fg: theme.accentMuted, bg: theme.panel }}
                />
              ))}
            <text content=" " style={{ bg: theme.panel }} />
            {sections.map((entry, index) => {
              const review = entry.targets.map((target) => reviewStatus(target.id, state));
              const reviewed = review.every((status) => status === "reviewed")
                ? "✓"
                : review.some((status) => status === "stale-reviewed")
                  ? "⚠"
                  : " ";
              const affected =
                state.checkpoint &&
                entry.targets.some((target) => checkpointStatus(target.id, state) !== "unchanged")
                  ? "•"
                  : " ";
              return (
                <text
                  key={entry.id}
                  content={fit(
                    ` ${entry.id === state.sectionId ? "→" : " "} ${index + 1}. ${reviewed !== " " ? `${reviewed} ` : ""}${affected !== " " ? `${affected} ` : ""}${entry.title}`,
                    innerWidth,
                  )}
                  style={{
                    fg: entry.id === state.sectionId ? theme.accent : theme.text,
                    bg: theme.panel,
                  }}
                  onMouseDown={(event) => {
                    if (event.button === 0) revealSection(entry.id);
                  }}
                />
              );
            })}
            {sections.length === 0 && (state.scope !== "changed" || unrepresented.length === 0) && (
              <text
                content={
                  state.scope === "changed"
                    ? " No changes since checkpoint."
                    : " All sections are hidden by filters."
                }
                style={{ fg: theme.muted }}
              />
            )}
            <text content=" " style={{ bg: theme.panel }} />
            {state.overview ? (
              wrap(
                state.guide.summary ?? "Choose a section to continue the guided review.",
                innerWidth - 1,
              ).map((line, index) => (
                <text
                  key={`summary:${index}`}
                  content={fit(` ${line}`, innerWidth)}
                  style={{ fg: theme.muted, bg: theme.panel }}
                />
              ))
            ) : section ? (
              <>
                {wrap(section.title, innerWidth - 1).map((line, index) => (
                  <text
                    key={`section-title:${index}`}
                    content={fit(` ${line}`, innerWidth)}
                    style={{ fg: theme.accent, bg: theme.panel }}
                  />
                ))}
                {wrap(section.explanation ?? "Review the targets in order.", innerWidth - 1).map(
                  (line, index) => (
                    <text
                      key={`explanation:${index}`}
                      content={fit(` ${line}`, innerWidth)}
                      style={{ fg: theme.muted, bg: theme.panel }}
                    />
                  ),
                )}
                <text content=" " style={{ bg: theme.panel }} />
                <text content=" Targets" style={{ fg: theme.text, bg: theme.panel }} />
                {section.targets
                  .filter(
                    (entry) =>
                      state.scope === "all" || checkpointStatus(entry.id, state) !== "unchanged",
                  )
                  .map((entry) => {
                    const status = checkpointStatus(entry.id, state);
                    const resolution = targetResolution(entry.id, state);
                    const statusLabel = state.checkpoint
                      ? targetCheckpointLabel(status)
                      : resolution?.status !== "resolved"
                        ? "? unavailable"
                        : "";
                    return (
                      <text
                        key={entry.id}
                        content={fit(
                          ` ${entry.id === target?.id ? "→" : " "} ${reviewGlyph(reviewStatus(entry.id, state))} ${statusLabel ? `${statusLabel} ` : ""}${entry.path}:${entry.startLine}${entry.endLine === entry.startLine ? "" : `-${entry.endLine}`}`,
                          innerWidth,
                        )}
                        style={{
                          fg:
                            entry.id === target?.id
                              ? theme.accent
                              : state.checkpoint
                                ? checkpointColor(status, theme)
                                : theme.text,
                          bg: theme.panel,
                        }}
                        onMouseDown={(event) => {
                          if (event.button === 0) reveal(entry.id);
                        }}
                      />
                    );
                  })}
                <text content=" " style={{ bg: theme.panel }} />
                <text
                  content={fit(` [${targetReviewed ? "✓" : " "}] target reviewed`, innerWidth)}
                  style={{ fg: targetReviewed ? theme.badgeAdded : theme.text, bg: theme.panel }}
                  onMouseDown={(event) => {
                    if (event.button === 0 && !toggleCurrentReviewed()) {
                      actions.notify("Current guide target cannot be marked reviewed", "warning");
                    }
                  }}
                />
                <text
                  content={fit(` [${sectionReviewed ? "✓" : " "}] section reviewed`, innerWidth)}
                  style={{ fg: sectionReviewed ? theme.badgeAdded : theme.text, bg: theme.panel }}
                  onMouseDown={(event) => {
                    if (event.button === 0 && !toggleCurrentSectionReviewed()) {
                      actions.notify("Current guide section has no resolvable targets", "warning");
                    }
                  }}
                />
              </>
            ) : null}
            {unrepresented.length > 0 && (
              <>
                <text content=" " style={{ bg: theme.panel }} />
                <text
                  content={fit(" Outside guide", innerWidth)}
                  style={{ fg: theme.text, bg: theme.panel }}
                />
                {unrepresented.map((file) => (
                  <text
                    key={file.path}
                    content={fit(
                      ` ${state.fileCheckpoint ? fileCheckpointLabel(file.status) : "•"} ${file.path}`,
                      innerWidth,
                    )}
                    style={{
                      fg: state.fileCheckpoint
                        ? checkpointColor(file.status, theme)
                        : theme.badgeNeutral,
                      bg: theme.panel,
                    }}
                  />
                ))}
              </>
            )}
            {state.lastError && (
              <text
                content={fit(` ⚠ ${state.lastError}`, innerWidth)}
                style={{ fg: theme.badgeRemoved, bg: theme.panel }}
              />
            )}
            <text content=" " style={{ bg: theme.panel }} />
            <text
              content={fit(` sections  ${previousSectionKey} / ${nextSectionKey}`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            <text
              content={fit(` targets   ${previousTargetKey} / ${nextTargetKey}`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            <text
              content={fit(` review target   ${targetReviewedKey}`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            <text
              content={fit(` review section  ${sectionReviewedKey}`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            <text
              content={fit(` context   ${presentationKey}`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            <text
              content={fit(` ${toggleKey} toggle`, innerWidth)}
              style={{ fg: theme.muted, bg: theme.panel }}
            />
            {state.provider.configured && (
              <>
                <text
                  content={fit(
                    ` generate  ${keybindings.getKeys("hunk-guide.generate")[0] ?? "menu"}`,
                    innerWidth,
                  )}
                  style={{ fg: theme.muted, bg: theme.panel }}
                />
                <text
                  content={fit(
                    ` cancel     ${keybindings.getKeys("hunk-guide.cancel-generation")[0] ?? "menu"}`,
                    innerWidth,
                  )}
                  style={{ fg: theme.muted, bg: theme.panel }}
                />
                {state.source?.kind === "generated" && !state.source.stale && (
                  <text
                    content={fit(
                      ` save guide  ${keybindings.getKeys("hunk-guide.save-generated")[0] ?? "menu"}`,
                      innerWidth,
                    )}
                    style={{ fg: theme.muted, bg: theme.panel }}
                  />
                )}
              </>
            )}
            <text content=" more: Extensions menu" style={{ fg: theme.muted, bg: theme.panel }} />
          </>
        ) : (
          <>
            <text content=" No guide loaded." style={{ fg: theme.muted, bg: theme.panel }} />
            {state.lastError && (
              <text
                content={fit(` ${state.lastError}`, innerWidth)}
                style={{ fg: theme.badgeRemoved, bg: theme.panel }}
              />
            )}
            {state.provider.configured ? (
              <>
                <text
                  content={fit(providerLine, innerWidth)}
                  style={{
                    fg: state.provider.status === "failed" ? theme.badgeRemoved : theme.muted,
                    bg: theme.panel,
                  }}
                />
                <text
                  content={fit(
                    ` generate  ${keybindings.getKeys("hunk-guide.generate")[0] ?? "menu"}`,
                    innerWidth,
                  )}
                  style={{ fg: theme.muted, bg: theme.panel }}
                />
                <text content=" or use the Extensions menu" style={{ fg: theme.muted }} />
              </>
            ) : (
              <text
                content=" Set HUNK_GUIDE_FILE or create .hunk/guide.json."
                style={{ fg: theme.muted, bg: theme.panel }}
              />
            )}
          </>
        )}
      </box>
    </scrollbox>
  );
}
